### ISSUE TITLE
bug: type inference won't work when `constructor` has no `stateMutability` property

### ISSUE THREAD

**Issue by chenxsan** [wagmi-dev/abitype#108] opened 2023-03-09 11:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### TypeScript Version

4.9.4

### Current Behavior

Type inference won't work when `constructor` in abi has no `stateMutability`:

```
[
    {
      type: 'constructor',
      inputs: [
        { type: 'address', name: 'token_addr' },
        { type: 'address', name: 'art_proxy' },
      ],
    },
    {
      name: 'balanceOf',
      type: 'function',
      stateMutability: 'view',
      inputs: [{ name: 'account', type: 'address' }],
      outputs: [{ type: 'uint256' }],
    },
    {
      name: 'totalSupply',
      type: 'function',
      stateMutability: 'view',
      inputs: [],
      outputs: [{ type: 'uint256' }],
    },
    {
      name: 'transfer',
      type: 'function',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'recipient', type: 'address' },
        { name: 'tokenId', type: 'uint256' },
      ],
      outputs: [{ type: 'bool' }],
    },
  ]
```
![CleanShot 2023-03-09 at 19 32 07@2x](https://user-images.githubusercontent.com/1091472/224010952-09aa34c6-b382-4fdf-a7ac-0316b83bb0b1.png)

### Expected Behavior

I would expect type inference functioning well in the above case as `stateMutability` isn't a required field per https://docs.soliditylang.org/en/v0.8.15/abi-spec.html#json 

![CleanShot 2023-03-09 at 19 33 40@2x](https://user-images.githubusercontent.com/1091472/224011296-ecd1931b-e29e-4cc8-967d-ee745c7fe3e8.png)

### Link to Minimal Reproducible Example ([TypeScript Playground](https://tsplay.dev/wjQvkW))

https://viem.sh/docs/typescript.html#contract-abis

### Steps To Reproduce

1. copy the code here https://viem.sh/docs/typescript.html#contract-abis
2. add below code to abi:

```
  {
      type: 'constructor',
      inputs: [
        { type: 'address', name: 'token_addr' },
        { type: 'address', name: 'art_proxy' },
      ],
    },
```
3. check types of `functionName`

### Anything else?

I believe this can be fixed by changing [`stateMutability of constructor`](https://github.com/wagmi-dev/abitype/blob/644e8b0bb98f317e7b47a20fdbe685bde6b2ee42/src/abi.ts#L156) to optional.

**Comment by Raiden1411** [comment] 2023-03-09 16:28
![image](https://user-images.githubusercontent.com/67233402/224085966-a3058c1f-ecfb-4cfc-9c7c-c2a5b258ada2.png)

This means if you don't define a state mutability (view, pure, payable) in your function or constructor, then the `stateMutability` will be inferred as `nonpayable` meaning that the `stateMutability` will always be present on the abi.
I don't think I've seen an compiled abi without the `stateMutability` property on it, either as a function or constructor.

Your suggested fix does work. So I will let @tmm share his thoughts on the matter.

**Comment by tmm** [comment] 2023-03-09 20:48
Agree with @Raiden1411's comment. @chenxsan Where did you get the ABI from? (block explorer, compiler output, etc.)

Going to close this out as expected behavior. Can discuss further once we know where the ABI came from.

**Closed by tmm** 2023-03-09 20:48 UTC

**Comment by chenxsan** [comment] 2023-03-10 00:52
> Agree with @Raiden1411's comment. @chenxsan Where did you get the ABI from? (block explorer, compiler output, etc.)
> 
> Going to close this out as expected behavior. Can discuss further once we know where the ABI came from.

Interesting, I get it from a canto explorer, see https://tuber.build/address/0x990efF367C6c4aece43c1E98099061c897730F27/contracts#address-tabs, that's when I found type inference won't work in my case.

Btw, let's say `stateMutability` is required for `constructor`, then is it possible to report error about the type of inline abi? Obviously `{
      type: 'constructor',
      inputs: [
        { type: 'address', name: 'token_addr' },
        { type: 'address', name: 'art_proxy' },
      ],
    }` isn't valid per `AbiConstructor`, it would be great typescript can report it. Otherwise we have to dig the problem ourselves.

**Comment by Raiden1411** [comment] 2023-03-10 10:08
@chenxsan If you take the source code from that link and compile it in remix, you will see that the `stateMutability` gets placed on the constructor's abi. You can also use the `IsAbi` type helper to check if the abi that you are using is within the abi spec.
Using your example, you will see that when using the type helper, it results in `false`.

@tmm could possibly make sense in bubbling up the error so that folks get the error message as the (function|event|error) name autocomplete suggestion, given that there are no throw types. Let me know what you think.

**Comment by tmm** [comment] 2023-03-11 02:21
Yeah, down if there's an easy way to bubble it up!

**Comment by Raiden1411** [comment] 2023-03-11 18:56
I have an idea that could make this work. I am testing it out and if it works I wil create a discussion on viem since I think the topic that we are discussing is more appropriate there since here we dont control those functions types here.

**Comment by Raiden1411** [comment] 2023-03-14 20:48
Discussion created [here](https://github.com/wagmi-dev/viem/discussions/201).
