### ISSUE TITLE
Abi `Zod` schema does not infer to `Abi` type

### ISSUE THREAD

**Issue by mathieu-bour** [wagmi-dev/abitype#189] opened 2023-09-11 12:10 UTC
### Describe the bug

The Zod `Abi` schema provided from `abitype/zod` does not match the `Abi` type from `abitype`

### Link to Minimal Reproducible Example

https://github.com/mathieu-bour/abitype-zod/blob/main/index.ts

### Steps To Reproduce

```ts
import { Abi } from 'abitype';
import { Abi as AbiSchema } from 'abitype/zod';

const result: Abi = AbiSchema.parse([]);
```

### Package Version

0.9.8

### TypeScript Version

5.2.2

### Anything else?

TypeScript error:

```
index.ts:4:7 - error TS2322: Type '({ type: "error"; name: string; inputs: AbiParameter[]; } | { type: "event"; name: string; inputs: (AbiParameter & { indexed?: boolean | undefined; })[]; anonymous?: boolean | undefined; } | ({ ...; } & ({ ...; } | ... 2 more ... | { ...; })))[]' is not assignable to type 'Abi'.
  Type '{ type: "error"; name: string; inputs: AbiParameter[]; } | { type: "event"; name: string; inputs: (AbiParameter & { indexed?: boolean | undefined; })[]; anonymous?: boolean | undefined; } | ({ ...; } & ({ ...; } | ... 2 more ... | { ...; }))' is not assignable to type 'AbiConstructor | AbiError | AbiEvent | AbiFallback | AbiFunction | AbiReceive'.
    Type '{ stateMutability: "pure" | "view" | "nonpayable" | "payable"; constant?: boolean | undefined; gas?: number | undefined; payable?: boolean | undefined; } & { type: "constructor"; inputs: AbiParameter[]; }' is not assignable to type 'AbiConstructor | AbiError | AbiEvent | AbiFallback | AbiFunction | AbiReceive'.
      Type '{ stateMutability: "pure" | "view" | "nonpayable" | "payable"; constant?: boolean | undefined; gas?: number | undefined; payable?: boolean | undefined; } & { type: "constructor"; inputs: AbiParameter[]; }' is missing the following properties from type 'AbiFunction': name, outputs

4 const result: Abi = AbiSchema.parse([]);
```

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wagmi-dev/abitype/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wagmi-dev/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guide](https://github.com/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md).

**Comment by Raiden1411** [comment] 2023-09-20 20:26
This is intended behavior. This comes down to the `Abi` type using the union of literals `"pure" | "view" | "nonpayable" | "payable"` and while zod does the same at runtime, at the typelevel it infers that as a `string` type and not their literal values and `string extends "anyliteralvalue"` is false so you get that type error when trying to assign that type to the type return from the zod schema parse

**Comment by mathieu-bour** [comment] 2023-09-21 13:12
The biggest problem is that it makes the Zod extension very difficult to use with abitype itself and viem by extension. I have to make horrible conversions like:

```import { Abi } from 'abitype';
import { Abi as AbiSchema } from 'abitype/zod';

const result: Abi = AbiSchema.parse([]) as unknown as Abi;
```

**Comment by Raiden1411** [comment] 2023-10-02 13:41
But why are you assign the ABI to the zod schema parsed? The zod type should be assignable to function were the args expect the `Abi` type. Here is an example https://tsplay.dev/w2vD9w

**Comment by mathieu-bour** [comment] 2023-10-02 14:14
My goal is to build a platform where users can submit ABIs via a form. To verify that the submitted data is a valid ABI, I am using `import { Abi as AbiSchema } from 'abitype/zod';` to check if the ABI is valid. If the ABI is valid, I will then use viem to interact with the contracts.

```ts
import { Abi } from 'abitype';
import { Abi as AbiSchema } from 'abitype/zod';

const validAbi: Abi = AbiSchema.parse(maybeNotAbi); // not assignable to Abi
```

To sum up, since the AbiSchema is provided by `abitype/zod`, I would expect a parsed zod Abi to be assignable to `abitype`'s `Abi`.

**Comment by Raiden1411** [comment] 2023-10-02 17:23
You can still do this without having to cast the parsed zod abi to `Abi`.

[Example](tsplay.dev/m3V0qN)

Take the example above. Its using viem's `getContract` function with the zod parsed abi. There is no need here to perform manual casting as this will also works.
[Viem docs](https://viem.sh/docs/contract/getContract.html#abi)

However i believed i have found the problem and it should be fixed with #192

**Comment by mathieu-bour** [comment] 2023-10-03 03:17
Thanks a lot for pointing this to me. While I fully agree that the provided code works, this issue was more about the fact that the Zod schema was not working with the abitype Abi type. However, since there full compatibility with viem, I would consider this issue as "nice-to-have".

I just checked your PR #192 and it looks like that it fixes the issue!

**Comment by tmm** [comment] 2023-10-03 15:53
`abitype@0.9.9`

**Closed by tmm** 2023-10-03 15:53 UTC
